package com.holovenko.smart_devices_simulator.message.enum

enum class MessageType {
    HOME_OWNER_DETECTED,
    SUSPICIOUS_ACTIVITY_OUTSIDE,
    SUSPICIOUS_ACTIVITY_INSIDE,
    COURIER_DETECTED,
    MUSIC_TO_LOUD,
    MUSIC_TO_QUITE,
    WORKOUT_MUSIC_ENABLED,
    SEX_MUSIC_ENABLED,
    LIGHT_ENABLED_IN_BRIGHT_PERIOD,
    LIGHT_EXPECTED_LIMIT_EXCEED,
    LIGHT_ENABLED_WHILE_SLEEPING,
    MORNING_ALARM_SKIPPED,
    MORNING_ALARM_DID_NOT_WORKED,
    MORNING_ALARM_TURNED_OFF_IN_TIME,
    TEMPERATURE_BELOW_COMFORTABLE,
    TEMPERATURE_ABOVE_COMFORTABLE,
    NIGHT_MODE_ENABLED,
    TEMPERATURE_MAINTAINING_ENABLED
}